version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  web:
    build:
      context: .
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080/health-check || exit 1
      interval: 10s
      retries: 20
      start_period: 20s
      timeout: 5s
    depends_on:
      - db
  populate_database:
    build: ./populate_database
    depends_on:
      web:
        condition: service_healthy
volumes:
  db:
    driver: local